name: 'Flagship'
description: 'Flagship CLI in github action'
author: 'Chadi LAOULAOU <chadiii> | AB Tasty'

# Define your inputs here.
inputs:
  create-configuration:
    description: 'create configuraiton'
    required: false

  use-configuration:
    description: 'use configuraiton'
    required: false

  list-flag:
    description: 'list flag'
    required: false
# Define your outputs here.
outputs:
  COMMAND_RESPONSE:
    description: 'result of the cli'

runs:
  using: node20
  main: dist/index.js
