name: 'Flagship'
description: 'CLI in action'
author: 'Chadi LAOULAOU <chadiii> | AB Tasty'

# Define your inputs here.
inputs:
  resource:
    description: 'Flagship resource'
    required: true
  
  method:
    description: 'method for the resource'
    required: true
  
  flags:
    description: 'flags for the method'
    required: false

# Define your outputs here.
outputs:
  result:
    description: 'result of the cli'

runs:
  using: node20
  main: dist/index.js
