name: 'Flagship'
description: 'Flagship CLI in github action'
author: 'Chadi LAOULAOU <chadiii> | AB Tasty'

# Define your inputs here.
inputs:
  resource:
    description: 'Flagship resource'
    required: true
  
  method:
    description: 'method for the resource'
    required: false
  
  flags:
    description: 'flags for the method'
    required: false

  create-configuration:
    description: 'create configuraiton'
    required: false
# Define your outputs here.
outputs:
  COMMAND_RESPONSE:
    description: 'result of the cli'

runs:
  using: node20
  main: dist/index.js
