on:
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  demo_abtasty_cli:
    runs-on: ubuntu-latest
    name: A job Test AB Tasty CLI in CI
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configuration
        uses: ./
        id: config
        with:
          fe-login-auth: |
            commandId: c1
            username: configuration-name
            client-id: ${{secrets.CLIENT_ID}}
            client-secret: ${{secrets.CLIENT_SECRET}}
            account-id: ${{secrets.ACCOUNT_ID}}
            account-environment-id: ${{secrets.ACCOUNT_ENVIRONMENT_ID}}

          fe-list-project: |
            commandId: c2
            output-format: json

          fe-load-resource: |
            commandId: c3
            file: resource-loader-templates/file-example.json
            input-params-file: resource-loader-templates/input-params-file-example.json
            output-format: json

      - name: Get previous configuration step response
        continue-on-error: true
        run: |
          echo "${{ steps.config.outputs.commandsResult}}"
