on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hello world action step
        continue-on-error: true
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          resource: 'configuration'
          method: 'create'
          flags: '-n,config-name,-i,ciAction,-s,csAction,-a,aAction,-e,eAction'

      - name: Get the output time
        run: echo "The time was ${{ toJson(steps.hello.outputs.result) }}"

      - name: List ls
        run: ls

      - name: List Flagship
        run: ls flagship

      - name: List version
        run: ls flagship/1.0

      - name: Run flagship version
        run: flagship/1.0/flagship version

      - name: Run flagship configuration
        run: flagship/1.0/flagship configuration list
