on: [push]

jobs:
  test_flagship_cli:
    runs-on: ubuntu-latest
    name: A job Test Flagship CLI in CI
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configuration
        uses: ./ # Uses an action in the root directory
        id: config
        with:
          create-configuration: '-n,config-name,-i,ciAction,-s,csAction,-a,aAction,-e,eAction'

      - name: Configuration
        uses: ./ # Uses an action in the root directory
        id: config1
        with:
          create-configuration: |
            name: configuration-name
            client_id: ci
            client_secret: cs
            account_id: ai
            account_environment_id: aei

      - name: Get previous configuration step response
        continue-on-error: true
        run: echo "${{ steps.config.outputs.COMMAND_RESPONSE}}"
