on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          resource: 'configuration'
          method: 'create'
          flags: "-i,ciAction,-s,csAction,-a,aAction,-e,eAction"
      
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.result }}"

      - name: List ls
        run: ls

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello1.outputs.result }}"
