on: [push]

jobs:
  test_flagship_cli:
    runs-on: ubuntu-latest
    name: A job Test Flagship CLI in CI
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configuration
        uses: ./ # Uses an action in the root directory
        id: config
        with:
          create-configuration: |
            name: configuration-name
            client-id: ${{secrets.CLIENT_ID}}
            client-secret: ${{secrets.CLIENT_SECRET}}
            account-id: ${{secrets.ACCOUNT_ID}}
            account-environment_id: ${{secrets.ACCOUNT_ENV_ID}}

          use-configuration: |
            name: configuration-name

          list-flag: |
            output-format: json

      - name: Get previous configuration step response
        continue-on-error: true
        run: echo "${{ steps.config.outputs.COMMAND_RESPONSE}}"

      - name: List ls
        run: ls -all

      - name: List ls runner
        run: ls /home/runner

      - name: List Flagship
        run: ls flagship

      - name: Run flagship version
        run: flagship/1.0.2/flagship version

      - name: mkdir
        run: mkdir /home/runner/.flagship

      - name: mkdir
        run: mkdir /home/runner/.flagship/configurations

      - name: Run flagship configuration
        working-directory: /home/runner/work/flagship-action/flagship-action
        run:
          flagship/1.0.2/flagship configuration create -n config-name-1 -i
          ciAction -s csAction -a aAction -e eAction

      - name: Run flagship configuration
        run: flagship/1.0.2/flagship configuration list
