on: [push]

jobs:
  test_flagship_cli:
    runs-on: ubuntu-latest
    name: A job Test Flagship CLI in CI
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configuration
        uses: ./ # Uses an action in the root directory
        id: config
        with:
          create-configuration: |
            name: configuration-name
            client-id: ${{secrets.CLIENT_ID}}
            client-secret: ${{secrets.CLIENT_SECRET}}
            account-id: ${{secrets.ACCOUNT_ID}}
            account-environment-id: ${{secrets.ACCOUNT_ENV_ID}}

          use-configuration: |
            name: configuration-name

          list-flag: |
            output-format: json

      - name: Get previous configuration step response
        continue-on-error: true
        run: echo "${{ steps.config.outputs.COMMAND_RESPONSE}}"
